import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { I18nManager } from 'react-native';
import * as Localization from 'expo-localization';

export type Language = 'en' | 'ar' | 'hi' | 'ur' | 'bn' | 'ta' | 'te' | 'ml' | 'kn' | 'gu';

export const LANGUAGE_NAMES: Record<Language, string> = {
  en: 'English',
  ar: 'العربية',
  hi: 'हिन्दी',
  ur: 'اردو',
  bn: 'বাংলা',
  ta: 'தமிழ்',
  te: 'తెలుగు',
  ml: 'മലയാളം',
  kn: 'ಕನ್ನಡ',
  gu: 'ગુજરાતી',
};

export const LANGUAGE_DESCRIPTIONS: Record<Language, string> = {
  en: 'Reflect in English',
  ar: 'تأمل باللغة العربية',
  hi: 'हिंदी में मनन करें',
  ur: 'اردو میں غور و فکر کریں',
  bn: 'বাংলায় চিন্তা করুন',
  ta: 'தமிழில் சிந்தியுங்கள்',
  te: 'తెలుగులో ఆలోచించండి',
  ml: 'മലയാളത്തിൽ ചിന്തിക്കുക',
  kn: 'ಕನ್ನಡದಲ್ಲಿ ಚಿಂತಿಸಿ',
  gu: 'ગુજરાતીમાં ચિંતન કરો',
};

export const INDIAN_LANGUAGES: Language[] = ['hi', 'ur', 'bn', 'ta', 'te', 'ml', 'kn', 'gu'];
export const RTL_LANGUAGES: Language[] = ['ar', 'ur'];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isLoaded: boolean;
  isIndia: boolean;
}

// Helper: get full language name for LLM instructions
export function getLanguageNameForLLM(lang: Language): string {
  const map: Record<Language, string> = {
    en: 'English',
    ar: 'Arabic',
    hi: 'Hindi',
    ur: 'Urdu',
    bn: 'Bengali',
    ta: 'Tamil',
    te: 'Telugu',
    ml: 'Malayalam',
    kn: 'Kannada',
    gu: 'Gujarati',
  };
  return map[lang];
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.reflect': 'Reflect',
    'nav.saved': 'Saved',
    'nav.quran': 'Qur\'an',
    'nav.wallpaper': 'Wallpaper',
    'nav.settings': 'Settings',
    'home.verseOfDay': 'Verse of the Day',
    'home.reflect': 'Reflect',
    'nav.prayer': 'Prayer',
    'chat.title': 'Reflection',
    'chat.empty': 'Share what is on your mind.\nLet us reflect together.',
    'chat.placeholder': 'Share your thoughts...',
    'chat.error': 'Unable to connect. Please try again.',
    'saved.title': 'Saved Verses',
    'saved.empty': "You haven't saved any verses yet.",
    'wallpaper.title': 'Lock Screen',
    'wallpaper.light': 'Light',
    'wallpaper.dark': 'Dark',
    'wallpaper.translation': 'Translation',
    'wallpaper.save': 'Save Wallpaper',
    'wallpaper.saved': 'Saved',
    'settings.title': 'Settings',
    'settings.preferences': 'Preferences',
    'settings.appearance': 'Appearance',
    'settings.appearanceDesc': 'Light or dark mode',
    'settings.language': 'Language',
    'settings.languageDesc': 'English / العربية',
    'settings.notifications': 'Prayer Reminders',
    'settings.notificationsDesc': 'Gentle notifications',
    'settings.activeDays': 'Active Days',
    'settings.notificationTimes': 'Notification Times',
    'settings.prayer.title': 'Prayer Notifications',
    'settings.prayer.desc': 'Frequency and times',
    'prayer.title': 'Prayer & Qibla',
    'prayer.qibla': 'Qibla Compass',
    'prayer.schedule': 'Prayer Schedule',
    'prayer.times.count': 'Prayers per day',
    'prayer.times.setup': 'Set Notification Times',
    'settings.about': 'About',
    'settings.aboutDesc': "MuslimSpace is a space for quiet reflection, grounded in the teachings of the Qur'an.",
    'settings.version': 'Version 1.1.0',
    'onboarding.step1.title': "Reflect through the Qur'an",
    'onboarding.step1.subtitle': 'Find relevant verses and guidance for real-life situations',
    'onboarding.continue': 'Continue',
    'onboarding.next': 'Next',
    'onboarding.skip': 'Skip',
    'onboarding.step2.title': "Share what's on your mind",
    'onboarding.step2.subtitle': 'You can type anything. The app finds relevant verses and helps you reflect.',
    'onboarding.step2.point1': "Relevant Qur'an verses",
    'onboarding.step2.point2': 'Short reflections',
    'onboarding.step2.point3': 'Practical guidance',
    'onboarding.step3.title': 'A tool for reflection',
    'onboarding.step3.p1': 'This app shares verses and insights based on established teachings.',
    'onboarding.step3.p2': 'It does not provide religious rulings or speak on behalf of Allah.',
    'onboarding.step3.btn': 'I understand',
    'onboarding.step4.title': 'What would you like help with?',
    'onboarding.step4.optional': 'Optional',
    'onboarding.step5.title': 'Start your first reflection',
    'onboarding.step5.placeholder': "What's on your mind?",
    'onboarding.step5.showVerse': "Show today's verse",
    'onboarding.qibla.title': 'Qibla Compass',
    'onboarding.qibla.desc': 'Find the direction of Makkah easily from anywhere in the world.',
    'onboarding.notifications.title': 'Prayer Reminders',
    'onboarding.notifications.desc': 'Set how many times you would like to be reminded to pray.',
    'onboarding.step2': 'Step 2 of 2',
    'onboarding.title': 'What are you feeling?',
    'onboarding.subtitle': 'Select any topics to start your reflection.',
    'onboarding.start': 'Start Reflection',
    'onboarding.moreLanguages': 'More Languages',
    'topics.anxiety': 'Anxiety',
    'topics.gratitude': 'Gratitude',
    'topics.patience': 'Patience',
    'topics.decision-making': 'Decision Making',
    'topics.grief': 'Grief',
    'topics.purpose': 'Purpose',
    'topics.relationships': 'Relationships',
    'topics.forgiveness': 'Forgiveness',
    'topics.inner-peace': 'Inner Peace',
    'topics.hardship': 'Hardship',
    'quran.surahs': 'Surahs',
    'quran.bookmarks': 'Bookmarks',
    'quran.ayah': 'Ayah',
    'quran.addedBookmark': 'Bookmark added',
    'quran.removedBookmark': 'Bookmark removed',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.reflect': 'تأمل',
    'nav.saved': 'المحفوظات',
    'nav.wallpaper': 'الخلفية',
    'nav.settings': 'الإعدادات',
    'home.verseOfDay': 'آية اليوم',
    'home.reflect': 'تأمل',
    'nav.prayer': 'الصلاة',
    'chat.title': 'تأمل',
    'chat.empty': 'شارك ما يدور في ذهنك.\nلنتأمل معاً.',
    'chat.placeholder': 'شارك أفكارك...',
    'chat.error': 'تعذر الاتصال. حاول مرة أخرى.',
    'saved.title': 'الآيات المحفوظة',
    'saved.empty': "لم تقم بحفظ أي آيات حتى الآن.",
    'wallpaper.title': 'شاشة القفل',
    'wallpaper.light': 'فاتح',
    'wallpaper.dark': 'داكن',
    'wallpaper.translation': 'الترجمة',
    'wallpaper.save': 'حفظ الخلفية',
    'wallpaper.saved': 'تم الحفظ',
    'settings.title': 'الإعدادات',
    'settings.preferences': 'التفضيلات',
    'settings.appearance': 'المظهر',
    'settings.appearanceDesc': 'الوضع الفاتح أو الداكن',
    'settings.language': 'اللغة',
    'settings.languageDesc': 'English / العربية',
    'settings.notifications': 'تذكير بالصلاة',
    'settings.notificationsDesc': 'إشعارات لطيفة',
    'settings.activeDays': 'الأيام النشطة',
    'settings.notificationTimes': 'أوقات الإشعارات',
    'settings.prayer.title': 'تذكير بالصلاة',
    'settings.prayer.desc': 'التكرار والأوقات',
    'prayer.title': 'الصلاة والقبلة',
    'prayer.qibla': 'بوصلة القبلة',
    'prayer.schedule': 'جدول الصلاة',
    'prayer.times.count': 'صلوات في اليوم',
    'prayer.times.setup': 'تعيين أوقات الإشعارات',
    'settings.about': 'حول',
    'settings.aboutDesc': "سكينة هي مساحة للتأمل الهادئ، مستمدة من تعاليم القرآن الكريم.",
    'settings.version': 'الإصدار 1.1.0',
    'onboarding.step1.title': 'تأمل من خلال القرآن',
    'onboarding.step1.subtitle': 'ابحث عن آيات وإرشادات ذات صلة بمواقف الحياة الواقعية',
    'onboarding.continue': 'متابعة',
    'onboarding.next': 'التالي',
    'onboarding.skip': 'تخطي',
    'onboarding.step2.title': 'شارك ما يدور في ذهنك',
    'onboarding.step2.subtitle': 'يمكنك كتابة أي شيء. يجد التطبيق آيات ذات صلة ويساعدك على التأمل.',
    'onboarding.step2.point1': 'آيات قرآنية ذات صلة',
    'onboarding.step2.point2': 'تأملات قصيرة',
    'onboarding.step2.point3': 'إرشادات عملية',
    'onboarding.step3.title': 'أداة للتأمل',
    'onboarding.step3.p1': 'يشارك هذا التطبيق آيات ورؤى مبنية على تعاليم راسخة.',
    'onboarding.step3.p2': 'لا يقدم فتاوى دينية ولا يتحدث باسم الله.',
    'onboarding.step3.btn': 'أفهم',
    'onboarding.step4.title': 'بماذا تريد المساعدة؟',
    'onboarding.step4.optional': 'اختياري',
    'onboarding.step5.title': 'ابدأ تأملك الأول',
    'onboarding.step5.placeholder': 'ما الذي يشغل بالك؟',
    'onboarding.step5.showVerse': 'عرض آية اليوم',
    'onboarding.qibla.title': 'بوصلة القبلة',
    'onboarding.qibla.desc': 'جد اتجاه مكة المكرمة بسهولة من أي مكان في العالم.',
    'onboarding.notifications.title': 'تذكير بالصلاة',
    'onboarding.notifications.desc': 'حدد كم مرة تود أن يتم تذكيرك بالصلاة.',
    'onboarding.step2': 'الخطوة ٢ من ٢',
    'onboarding.title': 'بماذا تشعر؟',
    'onboarding.subtitle': 'اختر أي موضوع لبدء التأمل.',
    'onboarding.start': 'ابدأ التأمل',
    'onboarding.moreLanguages': 'المزيد من اللغات',
    'topics.anxiety': 'القلق',
    'topics.gratitude': 'الامتنان',
    'topics.patience': 'الصبر',
    'topics.decision-making': 'اتخاذ القرار',
    'topics.grief': 'الحزن',
    'topics.purpose': 'الهدف',
    'topics.relationships': 'العلاقات',
    'topics.forgiveness': 'التسامح',
    'topics.inner-peace': 'السلام الداخلي',
    'topics.hardship': 'المشقة',
    'quran.surahs': 'السور',
    'quran.bookmarks': 'العلامات المرجعية',
    'quran.ayah': 'آية',
    'quran.addedBookmark': 'تمت إضافة العلامة',
    'quran.removedBookmark': 'تمت إزالة العلامة',
  },
  hi: {
    'nav.home': 'होम',
    'nav.reflect': 'चिंतन',
    'nav.saved': 'सहेजा गया',
    'nav.wallpaper': 'वॉलपेपर',
    'nav.settings': 'सेटिंग्स',
    'home.verseOfDay': 'आज की आयत',
    'home.reflect': 'चिंतन करें',
    'nav.prayer': 'प्रार्थना',
    'chat.title': 'चिंतन',
    'chat.empty': 'अपने मन की बात साझा करें।\nआइए साथ मिलकर चिंतन करें।',
    'chat.placeholder': 'अपने विचार साझा करें...',
    'chat.error': 'कनेक्ट नहीं हो पाया। कृपया पुनः प्रयास करें।',
    'saved.title': 'सहेजी गई आयतें',
    'saved.empty': 'आपने अभी तक कोई आयत सहेजी नहीं है।',
    'wallpaper.title': 'लॉक स्क्रीन',
    'wallpaper.light': 'लाइट',
    'wallpaper.dark': 'डार्क',
    'wallpaper.translation': 'अनुवाद',
    'wallpaper.save': 'वॉलपेपर सहेजें',
    'wallpaper.saved': 'सहेजा गया',
    'settings.title': 'सेटिंग्स',
    'settings.preferences': 'प्राथमिकताएँ',
    'settings.appearance': 'दिखावट',
    'settings.appearanceDesc': 'लाइट या डार्क मोड',
    'settings.language': 'भाषा',
    'settings.languageDesc': 'हिन्दी',
    'settings.about': 'परिचय',
    'settings.aboutDesc': 'सकीना क़ुरआन की शिक्षाओं पर आधारित शांत चिंतन का स्थान है।',
    'settings.version': 'संस्करण 1.1.0',
    'settings.prayer.title': 'प्रार्थना सूचनाएं',
    'settings.prayer.desc': 'आवृत्ति और समय',
    'prayer.title': 'प्रार्थना और क़िबला',
    'prayer.qibla': 'क़िबला कंपास',
    'prayer.schedule': 'प्रार्थना अनुसूची',
    'prayer.times.count': 'प्रति दिन प्रार्थना',
    'prayer.times.setup': 'समय निर्धारित करें',
    'onboarding.qibla.title': 'क़िबला कंपास',
    'onboarding.qibla.desc': 'दुनिया में कहीं से भी आसानी से मक्का की दिशा खोजें।',
    'onboarding.notifications.title': 'प्रार्थना अनुस्मारक',
    'onboarding.notifications.desc': 'चुनें कि आप दिन में कितनी बार प्रार्थना अनुस्मारक चाहते हैं।',
    'onboarding.step2': 'चरण 2 का 2',
    'onboarding.title': 'आप क्या महसूस कर रहे हैं?',
    'onboarding.subtitle': 'चिंतन शुरू करने के लिए कोई भी विषय चुनें।',
    'onboarding.start': 'चिंतन शुरू करें',
    'onboarding.moreLanguages': 'और भाषाएँ',
    'topics.anxiety': 'चिंता',
    'topics.gratitude': 'कृतज्ञता',
    'topics.patience': 'धैर्य',
    'topics.decision-making': 'निर्णय लेना',
    'topics.grief': 'शोक',
    'topics.purpose': 'उद्देश्य',
    'topics.relationships': 'रिश्ते',
    'topics.forgiveness': 'क्षमा',
    'topics.inner-peace': 'आंतरिक शांति',
    'topics.hardship': 'कठिनाई',
    'quran.surahs': 'सूरह',
    'quran.bookmarks': 'बुकमार्क्स',
    'quran.ayah': 'आयत',
    'quran.addedBookmark': 'बुकमार्क जोड़ा गया',
    'quran.removedBookmark': 'बुकमार्क हटाया गया',
  },
  ur: {
    'nav.home': 'ہوم',
    'nav.reflect': 'غور و فکر',
    'nav.saved': 'محفوظ شدہ',
    'nav.wallpaper': 'وال پیپر',
    'nav.settings': 'ترتیبات',
    'home.verseOfDay': 'آج کی آیت',
    'home.reflect': 'غور کریں',
    'nav.prayer': 'نماز',
    'chat.title': 'غور و فکر',
    'chat.empty': 'اپنے دل کی بات بتائیں۔\nآئیے مل کر غور و فکر کریں۔',
    'chat.placeholder': 'اپنے خیالات بتائیں...',
    'chat.error': 'رابطہ نہیں ہو سکا۔ دوبارہ کوشش کریں۔',
    'saved.title': 'محفوظ آیات',
    'saved.empty': 'آپ نے ابھی تک کوئی آیت محفوظ نہیں کی۔',
    'wallpaper.title': 'لاک اسکرین',
    'wallpaper.light': 'ہلکا',
    'wallpaper.dark': 'ڈارک',
    'wallpaper.translation': 'ترجمہ',
    'wallpaper.save': 'وال پیپر محفوظ کریں',
    'wallpaper.saved': 'محفوظ ہو گیا',
    'settings.title': 'ترتیبات',
    'settings.preferences': 'ترجیحات',
    'settings.appearance': 'ظاہری شکل',
    'settings.appearanceDesc': 'لائٹ یا ڈارک موڈ',
    'settings.language': 'زبان',
    'settings.languageDesc': 'اردو',
    'settings.about': 'تعارف',
    'settings.aboutDesc': 'سکینہ قرآن کریم کی تعلیمات پر مبنی پرسکون غور و فکر کی جگہ ہے۔',
    'settings.version': 'ورژن 1.1.0',
    'settings.prayer.title': 'نماز کی یاددہانی',
    'settings.prayer.desc': 'تعداد اور اوقات',
    'prayer.title': 'نماز اور قبلہ',
    'prayer.qibla': 'قبلہ نما',
    'prayer.schedule': 'نماز کا وقت',
    'prayer.times.count': 'روزانہ نماز کی تعداد',
    'prayer.times.setup': 'اوقات مقرر کریں',
    'onboarding.qibla.title': 'قبلہ نما',
    'onboarding.qibla.desc': 'دنیا میں کہیں سے بھی آسانی سے قبلہ کا رخ معلوم کریں۔',
    'onboarding.notifications.title': 'نماز کی یاددہانی',
    'onboarding.notifications.desc': 'منتخب کریں کہ آپ دن میں کتنی بار یاددہانی چاہتے ہیں۔',
    'onboarding.step2': 'مرحلہ 2 از 2',
    'onboarding.title': 'آپ کیا محسوس کر رہے ہیں؟',
    'onboarding.subtitle': 'غور و فکر شروع کرنے کیلیے کوئی بھی موضوع منتخب کریں۔',
    'onboarding.start': 'غور و فکر شروع کریں',
    'onboarding.moreLanguages': 'مزید زبانیں',
    'topics.anxiety': 'بے چینی',
    'topics.gratitude': 'شکرگزاری',
    'topics.patience': 'صبر',
    'topics.decision-making': 'فیصلہ سازی',
    'topics.grief': 'غم',
    'topics.purpose': 'مقصد',
    'topics.relationships': 'رشتے',
    'topics.forgiveness': 'معافی',
    'topics.inner-peace': 'اندرونی سکون',
    'topics.hardship': 'مشکل',
    'quran.surahs': 'سورتیں',
    'quran.bookmarks': 'بک مارکس',
    'quran.ayah': 'آیت',
    'quran.addedBookmark': 'بک مارک شامل کر دیا گیا',
    'quran.removedBookmark': 'بک مارک ہٹا دیا گیا',
  },
  bn: {
    'nav.home': 'হোম',
    'nav.reflect': 'চিন্তন',
    'nav.saved': 'সংরক্ষিত',
    'nav.wallpaper': 'ওয়ালপেপার',
    'nav.settings': 'সেটিংস',
    'home.verseOfDay': 'আজকের আয়াত',
    'home.reflect': 'চিন্তন করুন',
    'nav.prayer': 'প্রার্থনা',
    'chat.title': 'চিন্তন',
    'chat.empty': 'আপনার মনের কথা শেয়ার করুন।\nআসুন একসাথে চিন্তা করি।',
    'chat.placeholder': 'আপনার ভাবনা শেয়ার করুন...',
    'chat.error': 'সংযোগ করা যায়নি। আবার চেষ্টা করুন।',
    'saved.title': 'সংরক্ষিত আয়াত',
    'saved.empty': 'আপনি এখনো কোনো আয়াত সংরক্ষণ করেননি।',
    'wallpaper.title': 'লক স্ক্রিন',
    'wallpaper.light': 'লাইট',
    'wallpaper.dark': 'ডার্ক',
    'wallpaper.translation': 'অনুবাদ',
    'wallpaper.save': 'ওয়ালপেপার সংরক্ষণ করুন',
    'wallpaper.saved': 'সংরক্ষিত',
    'settings.title': 'সেটিংস',
    'settings.preferences': 'পছন্দসমূহ',
    'settings.appearance': 'চেহারা',
    'settings.appearanceDesc': 'লাইট বা ডার্ক মোড',
    'settings.language': 'ভাষা',
    'settings.languageDesc': 'বাংলা',
    'settings.about': 'সম্পর্কে',
    'settings.aboutDesc': 'সাকিনাহ কুরআনের শিক্ষার উপর ভিত্তি করে নীরব চিন্তনের একটি স্থান।',
    'settings.version': 'সংস্করণ 1.1.0',
    'settings.prayer.title': 'প্রার্থনা বিজ্ঞপ্তি',
    'settings.prayer.desc': 'ফ্রিকোয়েন্সি এবং সময়',
    'prayer.title': 'প্রার্থনা ও কিবলা',
    'prayer.qibla': 'কিবলা কম্পাস',
    'prayer.schedule': 'প্রার্থনা সময়সূচী',
    'prayer.times.count': 'প্রতি দিন প্রার্থনা',
    'prayer.times.setup': 'সময় নির্ধারণ করুন',
    'onboarding.qibla.title': 'কিবলা কম্পাস',
    'onboarding.qibla.desc': 'বিশ্বের যেকোনো প্রান্ত থেকে সহজেই মক্কার দিক খুঁজে নিন।',
    'onboarding.notifications.title': 'প্রার্থনা অনুস্মারক',
    'onboarding.notifications.desc': 'আপনি দিনে কতবার প্রার্থনা অনুস্মারক পেতে চান তা নির্ধারণ করুন।',
    'onboarding.step2': 'ধাপ ২ এর ২',
    'onboarding.title': 'আপনি কী অনুভব করছেন?',
    'onboarding.subtitle': 'চিন্তন শুরু করতে যেকোনো বিষয় নির্বাচন করুন।',
    'onboarding.start': 'চিন্তন শুরু করুন',
    'onboarding.moreLanguages': 'আরও ভাষা',
    'topics.anxiety': 'উদ্বেগ',
    'topics.gratitude': 'কৃতজ্ঞতা',
    'topics.patience': 'ধৈর্য',
    'topics.decision-making': 'সিদ্ধান্ত গ্রহণ',
    'topics.grief': 'শোক',
    'topics.purpose': 'উদ্দেশ্য',
    'topics.relationships': 'সম্পর্ক',
    'topics.forgiveness': 'ক্ষমা',
    'topics.inner-peace': 'অন্তর্শান্তি',
    'topics.hardship': 'কষ্ট',
    'quran.surahs': 'সূরা',
    'quran.bookmarks': 'বুকমার্ক',
    'quran.ayah': 'আয়াত',
    'quran.addedBookmark': 'বুকমার্ক যোগ করা হয়েছে',
    'quran.removedBookmark': 'বুকমার্ক সরানো হয়েছে',
  },
  ta: {
    'nav.home': 'முகப்பு',
    'nav.reflect': 'சிந்தனை',
    'nav.saved': 'சேமிக்கப்பட்டவை',
    'nav.wallpaper': 'வால்பேப்பர்',
    'nav.settings': 'அமைப்புகள்',
    'home.verseOfDay': 'இன்றைய வசனம்',
    'home.reflect': 'சிந்தியுங்கள்',
    'nav.prayer': 'தொழுகை',
    'chat.title': 'சிந்தனை',
    'chat.empty': 'உங்கள் மனதில் உள்ளதைப் பகிருங்கள்.\nஒன்றாகச் சிந்திப்போம்.',
    'chat.placeholder': 'உங்கள் எண்ணங்களைப் பகிருங்கள்...',
    'chat.error': 'இணைக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'saved.title': 'சேமிக்கப்பட்ட வசனங்கள்',
    'saved.empty': 'நீங்கள் இன்னும் வசனங்களை சேமிக்கவில்லை.',
    'wallpaper.title': 'பூட்டுத் திரை',
    'wallpaper.light': 'லைட்',
    'wallpaper.dark': 'டார்க்',
    'wallpaper.translation': 'மொழிபெயர்ப்பு',
    'wallpaper.save': 'வால்பேப்பர் சேமி',
    'wallpaper.saved': 'சேமிக்கப்பட்டது',
    'settings.title': 'அமைப்புகள்',
    'settings.preferences': 'விருப்பங்கள்',
    'settings.appearance': 'தோற்றம்',
    'settings.appearanceDesc': 'லைட் அல்லது டார்க் மோட்',
    'settings.language': 'மொழி',
    'settings.languageDesc': 'தமிழ்',
    'settings.about': 'பற்றி',
    'settings.aboutDesc': 'சகீனா குர்ஆனின் போதனைகளின் அடிப்படையிலான அமைதியான சிந்தனைக்கான இடம்.',
    'settings.version': 'பதிப்பு 1.1.0',
    'settings.prayer.title': 'தொழுகை அறிவிப்புகள்',
    'settings.prayer.desc': 'அதிவெண் மற்றும் நேரங்கள்',
    'prayer.title': 'தொழுகை மற்றும் கிப்லா',
    'prayer.qibla': 'கிப்லா திசைகாட்டி',
    'prayer.schedule': 'தொழுகை அட்டவணை',
    'prayer.times.count': 'ஒரு நாளைக்கு தொழுகைகள்',
    'prayer.times.setup': 'நேரங்களை அமைக்கவும்',
    'onboarding.qibla.title': 'கிப்லா திசைகாட்டி',
    'onboarding.qibla.desc': 'உலகின் எங்கிருந்தும் மக்காவின் திசையை எளிதாகக் கண்டறியவும்।',
    'onboarding.notifications.title': 'தொழுகை நினைவூட்டல்',
    'onboarding.notifications.desc': 'ஒரு நாளைக்கு எத்தனை முறை தொழுகை நினைவூட்டல் வேண்டும் என்பதை அமைக்கவும்।',
    'onboarding.step2': 'படி 2 இல் 2',
    'onboarding.title': 'நீங்கள் என்ன உணர்கிறீர்கள்?',
    'onboarding.subtitle': 'சிந்தனையைத் தொடங்க ஏதேனும் தலைப்புகளைத் தேர்ந்தெடுக்கவும்.',
    'onboarding.start': 'சிந்தனையைத் தொடங்கு',
    'onboarding.moreLanguages': 'மேலும் மொழிகள்',
    'topics.anxiety': 'கவலை',
    'topics.gratitude': 'நன்றி',
    'topics.patience': 'பொறுமை',
    'topics.decision-making': 'முடிவெடுத்தல்',
    'topics.grief': 'துக்கம்',
    'topics.purpose': 'நோக்கம்',
    'topics.relationships': 'உறவுகள்',
    'topics.forgiveness': 'மன்னிப்பு',
    'topics.inner-peace': 'உள்ளமைதி',
    'topics.hardship': 'கஷ்டம்',
    'quran.surahs': 'அத்தியாயங்கள்',
    'quran.bookmarks': 'புக்மார்க்குகள்',
    'quran.ayah': 'வசனம்',
    'quran.addedBookmark': 'புக்மார்க் சேர்க்கப்பட்டது',
    'quran.removedBookmark': 'புக்மார்க் நீக்கப்பட்டது',
  },
  te: {
    'nav.home': 'హోమ్',
    'nav.reflect': 'ఆలోచన',
    'nav.saved': 'సేవ్ చేయబడింది',
    'nav.wallpaper': 'వాల్‌పేపర్',
    'nav.settings': 'సెట్టింగ్‌లు',
    'home.verseOfDay': 'ఈ రోజు ఆయత్',
    'home.reflect': 'ఆలోచించండి',
    'nav.prayer': 'ప్రార్థన',
    'chat.title': 'ఆలోచన',
    'chat.empty': 'మీ మనసులో ఉన్నది పంచుకోండి.\nకలిసి ఆలోచిద్దాం.',
    'chat.placeholder': 'మీ ఆలోచనలు పంచుకోండి...',
    'chat.error': 'కనెక్ట్ కాలేదు. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    'saved.title': 'సేవ్ చేసిన ఆయతులు',
    'saved.empty': 'మీరు ఇంకా ఏ ఆయతులను సేవ్ చేయలేదు.',
    'wallpaper.title': 'లాక్ స్క్రీన్',
    'wallpaper.light': 'లైట్',
    'wallpaper.dark': 'డార్క్',
    'wallpaper.translation': 'అనువాదం',
    'wallpaper.save': 'వాల్‌పేపర్ సేవ్ చేయండి',
    'wallpaper.saved': 'సేవ్ అయింది',
    'settings.title': 'సెట్టింగ్‌లు',
    'settings.preferences': 'ప్రాధాన్యతలు',
    'settings.appearance': 'రూపం',
    'settings.appearanceDesc': 'లైట్ లేదా డార్క్ మోడ్',
    'settings.language': 'భాష',
    'settings.languageDesc': 'తెలుగు',
    'settings.about': 'గురించి',
    'settings.aboutDesc': 'సకీనా ఖురాన్ బోధనలపై ఆధారపడిన ప్రశాంత ఆలోచన కోసం ఒక స్థలం.',
    'settings.version': 'సంస్కరణ 1.1.0',
    'settings.prayer.title': 'ప్రార్థన నోటిఫికేషన్లు',
    'settings.prayer.desc': 'ఫ్రీక్వెన్సీ మరియు సమయాలు',
    'prayer.title': 'ప్రార్థన & ఖిబ్లా',
    'prayer.qibla': 'ఖిబ్లా కంపాస్',
    'prayer.schedule': 'ప్రార్థన సమయ పట్టిక',
    'prayer.times.count': 'రోజుకు ప్రార్థనలు',
    'prayer.times.setup': 'సమయాలను సెట్ చేయండి',
    'onboarding.qibla.title': 'ఖిబ్లా కంపాస్',
    'onboarding.qibla.desc': 'ప్రపంచంలో ఎక్కడి నుండైనా మక్కా దిశను సులభంగా కనుగొనండి।',
    'onboarding.notifications.title': 'ప్రార్థన రిమైండర్',
    'onboarding.notifications.desc': 'మీరు రోజుకు ఎన్నిసార్లు ప్రార్థన రిమైండర్ కోరుకుంటున్నారో సెట్ చేయండి।',
    'onboarding.step2': 'దశ 2 లో 2',
    'onboarding.title': 'మీరు ఏమి అనుభవిస్తున్నారు?',
    'onboarding.subtitle': 'ఆలోచన ప్రారంభించడానికి ఏదైనా అంశాన్ని ఎంచుకోండి.',
    'onboarding.start': 'ఆలోచన ప్రారంభించు',
    'onboarding.moreLanguages': 'మరిన్ని భాషలు',
    'topics.anxiety': 'ఆందోళన',
    'topics.gratitude': 'కృతజ్ఞత',
    'topics.patience': 'ఓర్పు',
    'topics.decision-making': 'నిర్ణయం తీసుకోవడం',
    'topics.grief': 'దుఃఖం',
    'topics.purpose': 'ఉద్దేశ్యం',
    'topics.relationships': 'సంబంధాలు',
    'topics.forgiveness': 'క్షమాపణ',
    'topics.inner-peace': 'అంతరిక శాంతి',
    'topics.hardship': 'కష్టం',
    'quran.surahs': 'సూరాలు',
    'quran.bookmarks': 'బుక్‌మార్క్‌లు',
    'quran.ayah': 'ఆయత్',
    'quran.addedBookmark': 'బుక్‌మార్క్ జోడించబడింది',
    'quran.removedBookmark': 'బుక్‌మార్క్ తీసివేయబడింది',
  },
  ml: {
    'nav.home': 'ഹോം',
    'nav.reflect': 'ചിന്തനം',
    'nav.saved': 'സേവ് ചെയ്തവ',
    'nav.wallpaper': 'വാൾപേപ്പർ',
    'nav.settings': 'ക്രമീകരണങ്ങൾ',
    'home.verseOfDay': 'ഇന്നത്തെ ആയത്ത്',
    'home.reflect': 'ചിന്തിക്കുക',
    'nav.prayer': 'പ്രാർത്ഥന',
    'chat.title': 'ചിന്തനം',
    'chat.empty': 'നിങ്ങളുടെ മനസ്സിലുള്ളത് പങ്കിടുക.\nനമുക്ക് ഒരുമിച്ച് ചിന്തിക്കാം.',
    'chat.placeholder': 'നിങ്ങളുടെ ചിന്തകൾ പങ്കിടുക...',
    'chat.error': 'കണക്ട് ചെയ്യാൻ കഴിഞ്ഞില്ല. വീണ്ടും ശ്രമിക്കുക.',
    'saved.title': 'സേവ് ചെയ്ത ആയത്തുകൾ',
    'saved.empty': 'നിങ്ങൾ ഇതുവരെ ആയത്തുകൾ സേവ് ചെയ്തിട്ടില്ല.',
    'wallpaper.title': 'ലോക്ക് സ്ക്രീൻ',
    'wallpaper.light': 'ലൈറ്റ്',
    'wallpaper.dark': 'ഡാർക്ക്',
    'wallpaper.translation': 'വിവർത്തനം',
    'wallpaper.save': 'വാൾപേപ്പർ സേവ് ചെയ്യുക',
    'wallpaper.saved': 'സേവ് ചെയ്തു',
    'settings.title': 'ക്രമീകരണങ്ങൾ',
    'settings.preferences': 'മുൻഗണനകൾ',
    'settings.appearance': 'രൂപം',
    'settings.appearanceDesc': 'ലൈറ്റ് അല്ലെങ്കിൽ ഡാർക്ക് മോഡ്',
    'settings.language': 'ഭാഷ',
    'settings.languageDesc': 'മലയാളം',
    'settings.about': 'കുറിച്ച്',
    'settings.aboutDesc': 'സകീന ഖുർആന്റെ പഠിപ്പിക്കലുകളിൽ അധിഷ്ഠിതമായ ശാന്തമായ ചിന്തനത്തിനുള്ള ഇടം.',
    'settings.version': 'പതിപ്പ് 1.1.0',
    'settings.prayer.title': 'പ്രാർത്ഥന അറിയിപ്പുകൾ',
    'settings.prayer.desc': 'ആവൃത്തിയും സമയവും',
    'prayer.title': 'പ്രാർത്ഥനയും ഖിബ്ലയും',
    'prayer.qibla': 'ഖിബ്ല കോമ്പസ്',
    'prayer.schedule': 'പ്രാർത്ഥന ഷെഡ്യൂൾ',
    'prayer.times.count': 'ഒരു ദിവസം പ്രാർത്ഥനകൾ',
    'prayer.times.setup': 'സമയങ്ങൾ ക്രമീകരിക്കുക',
    'onboarding.qibla.title': 'ഖിബ്ല കോമ്പസ്',
    'onboarding.qibla.desc': 'ലോകത്തെവിടെ നിന്നും മക്കയുടെ ദിശ എളുപ്പത്തിൽ കണ്ടെത്തുക।',
    'onboarding.notifications.title': 'പ്രാർത്ഥന ഓർമ്മപ്പെടുത്തൽ',
    'onboarding.notifications.desc': 'ഒരു ദിവസം എത്ര തവണ പ്രാർത്ഥന ഓർമ്മപ്പെടുത്തൽ വേണമെന്ന് നിശ്ചയിക്കുക।',
    'onboarding.step2': 'ഘട്ടം 2 ൽ 2',
    'onboarding.title': 'നിങ്ങൾ എന്താണ് അനുഭവിക്കുന്നത്?',
    'onboarding.subtitle': 'ചിന്തനം ആരംഭിക്കാൻ ഏതെങ്കിലും വിഷയങ്ങൾ തിരഞ്ഞെടുക്കുക.',
    'onboarding.start': 'ചിന്തനം ആരംഭിക്കുക',
    'onboarding.moreLanguages': 'കൂടുതൽ ഭാഷകൾ',
    'topics.anxiety': 'ഉത്കണ്ഠ',
    'topics.gratitude': 'നന്ദി',
    'topics.patience': 'ക്ഷമ',
    'topics.decision-making': 'തീരുമാനം എടുക്കൽ',
    'topics.grief': 'ദുഃഖം',
    'topics.purpose': 'ഉദ്ദേശ്യം',
    'topics.relationships': 'ബന്ധങ്ങൾ',
    'topics.forgiveness': 'ക്ഷമ',
    'topics.inner-peace': 'ആന്തരിക സമാധാനം',
    'topics.hardship': 'കഷ്ടപ്പാട്',
    'quran.surahs': 'സൂറത്തുകൾ',
    'quran.bookmarks': 'ബുക്ക്മാർക്കുകൾ',
    'quran.ayah': 'ആയത്ത്',
    'quran.addedBookmark': 'ബുക്ക്മാർക്ക് ചേർത്തു',
    'quran.removedBookmark': 'ബുക്ക്മാർക്ക് നീക്കി',
  },
  kn: {
    'nav.home': 'ಮುಖಪುಟ',
    'nav.reflect': 'ಚಿಂತನೆ',
    'nav.saved': 'ಉಳಿಸಿದವು',
    'nav.wallpaper': 'ವಾಲ್‌ಪೇಪರ್',
    'nav.settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'home.verseOfDay': 'ಇಂದಿನ ಆಯತ್',
    'home.reflect': 'ಚಿಂತಿಸಿ',
    'nav.prayer': 'ಪ್ರಾರ್ಥನೆ',
    'chat.title': 'ಚಿಂತನೆ',
    'chat.empty': 'ನಿಮ್ಮ ಮನಸ್ಸಿನಲ್ಲಿರುವುದನ್ನು ಹಂಚಿಕೊಳ್ಳಿ.\nಒಟ್ಟಿಗೆ ಚಿಂತಿಸೋಣ.',
    'chat.placeholder': 'ನಿಮ್ಮ ಆಲೋಚನೆಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ...',
    'chat.error': 'ಸಂಪರ್ಕಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'saved.title': 'ಉಳಿಸಿದ ಆಯತ್‌ಗಳು',
    'saved.empty': 'ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಆಯತ್‌ಗಳನ್ನು ಉಳಿಸಿಲ್ಲ.',
    'wallpaper.title': 'ಲಾಕ್ ಸ್ಕ್ರೀನ್',
    'wallpaper.light': 'ಲೈಟ್',
    'wallpaper.dark': 'ಡಾರ್ಕ್',
    'wallpaper.translation': 'ಅನುವಾದ',
    'wallpaper.save': 'ವಾಲ್‌ಪೇಪರ್ ಉಳಿಸಿ',
    'wallpaper.saved': 'ಉಳಿಸಲಾಗಿದೆ',
    'settings.title': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'settings.preferences': 'ಆದ್ಯತೆಗಳು',
    'settings.appearance': 'ನೋಟ',
    'settings.appearanceDesc': 'ಲೈಟ್ ಅಥವಾ ಡಾರ್ಕ್ ಮೋಡ್',
    'settings.language': 'ಭಾಷೆ',
    'settings.languageDesc': 'ಕನ್ನಡ',
    'settings.about': 'ಕುರಿತು',
    'settings.aboutDesc': 'ಸಕೀನಾ ಖುರ್ಆನ್ ಬೋಧನೆಗಳ ಆಧಾರದ ಮೇಲೆ ಶಾಂತ ಚಿಂತನೆಗಾಗಿ ಒಂದು ಸ್ಥಳ.',
    'settings.version': 'ಆವೃತ್ತಿ 1.1.0',
    'settings.prayer.title': 'ಪ್ರಾರ್ಥನೆ ಅಧಿಸೂಚನೆಗಳು',
    'settings.prayer.desc': 'ಆವರ್ತನ ಮತ್ತು ಸಮಯಗಳು',
    'prayer.title': 'ಪ್ರಾರ್ಥನೆ ಮತ್ತು ಕಿಬ್ಲಾ',
    'prayer.qibla': 'ಕಿಬ್ಲಾ ದಿಕ್ಸೂಚಿ',
    'prayer.schedule': 'ಪ್ರಾರ್ಥನೆ ವೇಳಾಪಟ್ಟಿ',
    'prayer.times.count': 'ದಿನಕ್ಕೆ ಪ್ರಾರ್ಥನೆಗಳು',
    'prayer.times.setup': 'ಸಮಯಗಳನ್ನು ಹೊಂದಿಸಿ',
    'onboarding.qibla.title': 'ಕಿಬ್ಲಾ ದಿಕ್ಸೂಚಿ',
    'onboarding.qibla.desc': 'ಜಗತ್ತಿನ ಎಲ್ಲಿಂದಲಾದರೂ ಮಕ್ಕಾದ ದಿಕ್ಕನ್ನು ಸುಲಭವಾಗಿ ಪತ್ತೆಹಚ್ಚಿ।',
    'onboarding.notifications.title': 'ಪ್ರಾರ್ಥನೆ ಜ್ಞಾಪನೆ',
    'onboarding.notifications.desc': 'ದಿನಕ್ಕೆ ಎಷ್ಟು ಬಾರಿ ಪ್ರಾರ್ಥನೆ ಜ್ಞಾಪನೆ ಬೇಕು ಎಂದು ಹೊಂದಿಸಿ।',
    'onboarding.step2': 'ಹಂತ 2 ರಲ್ಲಿ 2',
    'onboarding.title': 'ನೀವು ಏನು ಅನುಭವಿಸುತ್ತಿದ್ದೀರಿ?',
    'onboarding.subtitle': 'ಚಿಂತನೆ ಪ್ರಾರಂಭಿಸಲು ಯಾವುದೇ ವಿಷಯಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    'onboarding.start': 'ಚಿಂತನೆ ಪ್ರಾರಂಭಿಸಿ',
    'onboarding.moreLanguages': 'ಹೆಚ್ಚಿನ ಭಾಷೆಗಳು',
    'topics.anxiety': 'ಆತಂಕ',
    'topics.gratitude': 'ಕೃತಜ್ಞತೆ',
    'topics.patience': 'ತಾಳ್ಮೆ',
    'topics.decision-making': 'ನಿರ್ಧಾರ ತೆಗೆದುಕೊಳ್ಳುವಿಕೆ',
    'topics.grief': 'ದುಃಖ',
    'topics.purpose': 'ಉದ್ದೇಶ',
    'topics.relationships': 'ಸಂಬಂಧಗಳು',
    'topics.forgiveness': 'ಕ್ಷಮೆ',
    'topics.inner-peace': 'ಆಂತರಿಕ ಶಾಂತಿ',
    'topics.hardship': 'ಕಷ್ಟ',
    'quran.surahs': 'ಸೂರಾ',
    'quran.bookmarks': 'ಬುಕ್‌ಮಾರ್ಕ್‌ಗಳು',
    'quran.ayah': 'ಆಯತ್',
    'quran.addedBookmark': 'ಬುಕ್‌ಮಾರ್ಕ್ ಸೇರಿಸಲಾಗಿದೆ',
    'quran.removedBookmark': 'ಬುಕ್‌ಮಾರ್ಕ್ ತೆಗೆದುಹಾಕಲಾಗಿದೆ',
  },
  gu: {
    'nav.home': 'હોમ',
    'nav.reflect': 'ચિંતન',
    'nav.saved': 'સાચવેલું',
    'nav.wallpaper': 'વૉલપેપર',
    'nav.settings': 'સેટિંગ્સ',
    'home.verseOfDay': 'આજની આયત',
    'home.reflect': 'ચિંતન કરો',
    'nav.prayer': 'પ્રાર્થના',
    'chat.title': 'ચિંતન',
    'chat.empty': 'તમારા મનની વાત શેર કરો.\nચાલો સાથે મળીને ચિંતન કરીએ.',
    'chat.placeholder': 'તમારા વિચારો શેર કરો...',
    'chat.error': 'કનેક્ટ થઈ શક્યું નહીં. ફરી પ્રયાસ કરો.',
    'saved.title': 'સાચવેલી આયતો',
    'saved.empty': 'તમે હજુ સુધી કોઈ આયત સાચવી નથી.',
    'wallpaper.title': 'લૉક સ્ક્રીન',
    'wallpaper.light': 'લાઇટ',
    'wallpaper.dark': 'ડાર્ક',
    'wallpaper.translation': 'અનુવાદ',
    'wallpaper.save': 'વૉલપેપર સાચવો',
    'wallpaper.saved': 'સાચવાયું',
    'settings.title': 'સેટિંગ્સ',
    'settings.preferences': 'પસંદગીઓ',
    'settings.appearance': 'દેખાવ',
    'settings.appearanceDesc': 'લાઇટ અથવા ડાર્ક મોડ',
    'settings.language': 'ભાષા',
    'settings.languageDesc': 'ગુજરાતી',
    'settings.about': 'વિશે',
    'settings.aboutDesc': 'સકીનાહ કુરઆનના ઉપદેશો પર આધારિત શાંત ચિંતન માટેનું સ્થળ છે.',
    'settings.version': 'આવૃત્તિ 1.1.0',
    'settings.prayer.title': 'પ્રાર્થના સૂચનાઓ',
    'settings.prayer.desc': 'આવૃત્તિ અને સમય',
    'prayer.title': 'પ્રાર્થના અને કિબલા',
    'prayer.qibla': 'કિબલા હોકાયંત્ર',
    'prayer.schedule': 'પ્રાર્થના સમયપત્રક',
    'prayer.times.count': 'દિવસ દીઠ પ્રાર્થના',
    'prayer.times.setup': 'સમય સેટ કરો',
    'onboarding.qibla.title': 'કિબલા હોકાયંત્ર',
    'onboarding.qibla.desc': 'દુનિયામાં ગમે ત્યાંથી સરળતાથી મક્કાની દિશા શોધો।',
    'onboarding.notifications.title': 'પ્રાર્થના રીમાઇન્ડર',
    'onboarding.notifications.desc': 'તમે દિવસમાં કેટલી વાર પ્રાર્થના રીમાઇન્ડર માંગો છો તે સેટ કરો।',
    'onboarding.step2': 'પગલું 2 માંથી 2',
    'onboarding.title': 'તમે શું અનુભવો છો?',
    'onboarding.subtitle': 'ચિંતન શરૂ કરવા માટે કોઈપણ વિષય પસંદ કરો.',
    'onboarding.start': 'ચિંતન શરૂ કરો',
    'onboarding.moreLanguages': 'વધુ ભાષાઓ',
    'topics.anxiety': 'ચિંતા',
    'topics.gratitude': 'આભાર',
    'topics.patience': 'ધીરજ',
    'topics.decision-making': 'નિર્ણય લેવો',
    'topics.grief': 'શોક',
    'topics.purpose': 'હેતુ',
    'topics.relationships': 'સંબંધો',
    'topics.forgiveness': 'માફી',
    'topics.inner-peace': 'આંતરિક શાંતિ',
    'topics.hardship': 'મુશ્કેલી',
    'quran.surahs': 'સુરાહ',
    'quran.bookmarks': 'બુકમાર્ક્સ',
    'quran.ayah': 'આયત',
    'quran.addedBookmark': 'બુકમાર્ક ઉમેરાયો',
    'quran.removedBookmark': 'બુકમાર્ક દૂર કર્યો',
  },
};

// Detect if user is in India based on timezone or locale
export function detectIsIndia(): boolean {
  try {
    const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    if (timezone === 'Asia/Kolkata' || timezone === 'Asia/Calcutta') {
      return true;
    }
    // Check device locales for Indian language codes
    const locales = Localization.getLocales();
    const indianLocaleCodes = ['hi', 'bn', 'ta', 'te', 'ml', 'kn', 'gu', 'mr', 'pa', 'or', 'as', 'ur-IN'];
    for (const loc of locales) {
      if (loc.languageCode && indianLocaleCodes.includes(loc.languageCode)) return true;
      if (loc.regionCode === 'IN') return true;
    }
  } catch (e) {
    // Fallback: not India
  }
  return false;
}

const ALL_LANGUAGES: Language[] = ['en', 'ar', 'hi', 'ur', 'bn', 'ta', 'te', 'ml', 'kn', 'gu'];

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');
  const [isLoaded, setIsLoaded] = useState(false);
  const [isIndia, setIsIndia] = useState(false);

  useEffect(() => {
    setIsIndia(detectIsIndia());

    const loadLanguage = async () => {
      try {
        const saved = await AsyncStorage.getItem('sakinah_language') as Language;
        if (saved && ALL_LANGUAGES.includes(saved)) {
          setLanguageState(saved);
          const isRTL = RTL_LANGUAGES.includes(saved);
          if (I18nManager.isRTL !== isRTL) {
            I18nManager.forceRTL(isRTL);
          }
        }
      } catch (e) {
        console.warn('LanguageContext loadLanguage error:', e);
      } finally {
        setIsLoaded(true);
      }
    };
    loadLanguage();
  }, []);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    await AsyncStorage.setItem('sakinah_language', lang);
    const isRTL = RTL_LANGUAGES.includes(lang);
    if (I18nManager.isRTL !== isRTL) {
      I18nManager.forceRTL(isRTL);
    }
  };

  const t = (key: string) => {
    // Fallback chain: selected language -> English
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isLoaded, isIndia }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
